name: Test Workflows

on:
  push:
    branches: [ master, beta ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test
        run: |
          echo "Testing workflows..."
          echo "All workflows are working!"
